services:
  sonarqube:
    image: sonarqube:26.7.0.124771-community # SonarQube 버전 지정
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      # 선택사항(각 엔진별 Heap 사이즈 설정)
      SONAR_WEB_JAVAOPTS: "-Xms1024m -Xmx1024m"
      SONAR_CE_JAVAOPTS: "-Xms1024m -Xmx1024m"
      SONAR_SEARCH_JAVAOPTS: "-Xms1024m -Xmx1024m"
    volumes: # VM의 데이터영역 지정
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_temp:/opt/sonarqube/temp
    ports:
      - "9000:9000"
    networks: # 선택사항
      - ${NETWORK_TYPE:-ipv4}
    restart: always

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
    networks: # 선택사항
      - ${NETWORK_TYPE:-ipv4}
    restart: always

#volumes:
#  sonarqube_data:
#  sonarqube_temp:
#  sonarqube_extensions:
#  sonarqube_logs:
#  postgresql:
#  postgresql_data:
  
# 위 networks 속성을 사용하지 않을 경우 아래 설정 불필요
networks:
  ipv4:
    driver: bridge
    enable_ipv6: false
  dual:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"
        - subnet: "2001:db8:2::/64"
          gateway: "2001:db8:2::1"
