version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-33306
    restart: always
    ports:
      - "33306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: my_database
      TZ: Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: