version: '3.1'
services:
    mariadb:
      image: mariadb:latest
      container_name: mariadb-compose
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: example_db
        TZ: Asia/Seoul
      ports:
        - "3306:3306"
      volumes:
        - ./mariadb_data:/var/lib/mysql
volumes:
    mariadb_data: